networks:
  servarrnetwork:
    driver: ipvlan
    driver_opts:
      parent: enp6s18
    ipam:
      config:
        - subnet: 192.168.30.0/24
          gateway: 192.168.30.1

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.2
    ports:
      - "8080:8080"
      - "50000:50000/tcp"
      - "50000:50000/udp"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
      - WEBUI_PORT=8080
      - TORRENTING_PORT=50000
    volumes:
      - /media/.arr_configs/qbittorrent:/config
      - /media:/media
    restart: unless-stopped
    healthcheck:
      test: ping -c 1 openwrt.org || exit 1
      interval: 180s
      retries: 3
      start_period: 20s
      timeout: 10s

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=America/Denver
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.3
    ports:
      - "9696:9696"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/prowlarr:/config
      - /media:/media
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.4
    ports:
      - "7878:7878"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/radarr:/config
      - /media:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.5
    ports:
      - "8989:8989"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/sonarr:/config
      - /media:/media
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.6
    ports:
      - "8686:8686"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/lidarr:/config
      - /media:/media
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.7
    ports:
      - "6767:6767"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/bazarr:/config
      - /media:/media
    restart: unless-stopped

  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.8
    ports:
      - "5055:5055"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/jellyseer:/config
      - /media:/media
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.9
    ports:
      - "7575:7575"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/homarr:/config
      - /media:/media
    restart: unless-stopped

  whisparr:
    image: ghcr.io/hotio/whisparr:latest
    container_name: whisparr
    networks:
      servarrnetwork:
        ipv4_address: 192.168.30.10
    ports:
      - "6969:6969"
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/Denver
    volumes:
      - /media/.arr_configs/whisparr:/config
      - /media:/media
    restart: unless-stopped
